services:
  db:
    image: postgres:16
    container_name: habit-tracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: habit_tracker
    ports:
      - "5432:5432"
    volumes:
      - habit_tracker_pg:/var/lib/postgresql/data

volumes:
  habit_tracker_pg:
